name: Update Organization Readme

# This allows the workflow to be used as a reusable workflow
on:
  workflow_call:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    if: github.repository != 'jerobas/.github'

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Clone the .github repository
      - name: Clone .github repository
        run: |
          mkdir global-repo
          cd global-repo
          git clone https://github.com/jerobas/.github.git
          git rev-parse HEAD  # This prints the latest commit SHA1

      - name: Clone auto-readme repository
        run: |
          cd global-repo
          git clone https://github.com/jerobas/auto-readme.git
          git rev-parse HEAD  # This prints the latest commit SHA1

      # Step 3: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Specify your Python version

      # Step 4: Install dependencies (if any)
      - name: Install dependencies
        run: |
          cd global-repo/auto-readme
          pip install -r requirements.txt

      # Step 5: Run the Python file that compares README
      - name: Run comparison script
        run: |
          cd global-repo/auto-readme
          python compare_readme.py  # This is the Python file to compare and modify README if necessary

      # Step 6: Check for changes and commit if needed
      - name: Commit and push changes if README was updated
        run: |
          cd global-repo/.github
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

          echo "PAT Token is: $PAT_TOKEN"
          
          # Add the GITHUB_TOKEN to the remote URL for authentication
          git remote set-url origin https://x-access-token:$PAT_TOKEN@github.com/jerobas/.github.git

          git add profile/readme.md
          git diff-index --quiet HEAD || git commit -m "Updated README from new commit"
          git push
